// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddOrUpdateSetting(arg1:models.Setting):Promise<void>;

export function AddTask(arg1:models.Task):Promise<void>;

export function GetIssueByRepo(arg1:string,arg2:string):Promise<Array<models.Issue>>;

export function GetIssuesByRepoId(arg1:number):Promise<Array<models.Issue>>;

export function GetIssuesRemoteWithPagination(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<Array<models.Issue>>;

export function GetLanguages():Promise<Array<string>>;

export function GetReposByLanguage(arg1:string,arg2:number,arg3:number):Promise<Array<models.Repository>>;

export function GetReposByName(arg1:string,arg2:number,arg3:number):Promise<Array<models.Repository>>;

export function GetTasks():Promise<Array<models.Task>>;

export function Greet(arg1:string):Promise<string>;

export function SyncStaredRepos():Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<void>;
