// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOrUpdateSetting(arg1) {
  return window['go']['main']['App']['AddOrUpdateSetting'](arg1);
}

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function GetIssueByRepo(arg1, arg2) {
  return window['go']['main']['App']['GetIssueByRepo'](arg1, arg2);
}

export function GetIssuesByRepoId(arg1) {
  return window['go']['main']['App']['GetIssuesByRepoId'](arg1);
}

export function GetIssuesRemoteWithPagination(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetIssuesRemoteWithPagination'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetReposByLanguage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReposByLanguage'](arg1, arg2, arg3);
}

export function GetReposByName(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReposByName'](arg1, arg2, arg3);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SyncStaredRepos() {
  return window['go']['main']['App']['SyncStaredRepos']();
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
